[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar /app/app.jar"

# healthcheckPath = "/actuator/health"
# healthcheckTimeout = 300
