[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300