spring.application.name=ecommerce

#server port
server.port=8000

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=Xz9cwpNqm2DG6W2+z8ltTBHrgyfRdLD1gU4jksBw824=

# Swagger UI Custom Path
springdoc.swagger-ui.path=/swagger-ui.html

# Admin configuration
admin.email=admin@ecommerce.com
admin.password=Admin@456
admin.firstName=Admin
admin.lastName=User
admin.phoneNumber=+254726509023
admin.key=y2BcE8fL9pQ7rT3sX5vZ1mD4nG6hJ8kA

