
# Set active profile (default is "dev" if SPRING_PROFILE is not set)
#spring.profiles.active=${SPRING_PROFILE:dev}


spring.application.name=comm

# Server port
server.port=8000

# Database Configuration (hardcoded values)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomerce
spring.datasource.username=postgres
spring.datasource.password=hezron

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

jwt.secret=Xz9cwpNqm2DG6W2+z8ltTBHrgyfRdLD1gU4jksBw824=
jwt.expiration=86400000

# Swagger UI Custom Path
springdoc.swagger-ui.path=/swagger-ui.html

# Admin configuration
admin.email=admin@ecommerce.com
admin.password=Admin@456
admin.firstName=Admin
admin.lastName=User
admin.phoneNumber=+254726509023
admin.key=y2BcE8fL9pQ7rT3sX5vZ1mD4nG6hJ8kA

# Enable CORS globally
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Stripe Configuration
stripe.api.key=sk_test_51QzwVsA0htWb9UVOQ2708T9pahrHkYc3Lxsc3fuhoy3WA3PO43KJrH9Hu3RMYLJkHMg7VIcSe7Q9PgWEldvSKZl900bJAPck7p
stripe.webhook.secret=your_stripe_webhook_secret

# Application settings
app.currency=USD
